From jupyter/datascience-notebook
MAINTAINER Taku Yoshioka <taku.yoshioka.4096@gmail.com>

RUN pip install matplotlib==1.5.3 sphinx nbsphinx sphinx_rtd_theme \
    numpydoc parse sphinxcontrib-bibtex sphinx_bootstrap_theme \
    sphinxbootstrap4theme
ENV MPLBACKEND Agg